package codegen

import (
	"fmt"
	"os"
	"path"
	"strings"
	"text/template"

	"golang.org/x/mod/modfile"
)

// ModuleImportPath reads the module path from goModPath and joins it with the
// cleaned migrations directory to produce the import path of the migrations
// package (e.g. module github.com/me/app + ./migrations →
// github.com/me/app/migrations).
func ModuleImportPath(goModPath, migrationsDir string) (string, error) {
	data, err := os.ReadFile(goModPath)
	if err != nil {
		return "", fmt.Errorf("reading %q: %w", goModPath, err)
	}
	mod := modfile.ModulePath(data)
	if mod == "" {
		return "", fmt.Errorf("no module path found in %q", goModPath)
	}
	cleaned := path.Clean(strings.TrimPrefix(filepathToSlash(migrationsDir), "./"))
	cleaned = strings.TrimPrefix(cleaned, "/")
	if cleaned == "" || cleaned == "." {
		return mod, nil
	}
	return mod + "/" + cleaned, nil
}

// filepathToSlash normalizes OS path separators to forward slashes.
func filepathToSlash(p string) string {
	return strings.ReplaceAll(p, "\\", "/")
}

// runnerData is the template payload for the runner entrypoint.
type runnerData struct {
	MigrationsImport string
}

var runnerTmpl = template.Must(template.New("runner").Parse(`// Code generated by pigration. DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"os"
	"strconv"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/jorgejr568/pigration/migrator"

	_ "{{.MigrationsImport}}"
)

func main() {
	ctx := context.Background()

	dsn := os.Getenv("PIGRATION_DSN")
	if dsn == "" {
		fmt.Fprintln(os.Stderr, "pigration: PIGRATION_DSN is empty")
		os.Exit(1)
	}

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "pigration: connecting: %v\n", err)
		os.Exit(1)
	}
	defer pool.Close()

	var opts []migrator.RunOption
	if table := os.Getenv("PIGRATION_TABLE"); table != "" {
		opts = append(opts, migrator.WithOptions(migrator.Options{Table: table}))
	}
	if s := os.Getenv("PIGRATION_STEPS"); s != "" {
		n, err := strconv.Atoi(s)
		if err != nil {
			fmt.Fprintf(os.Stderr, "pigration: invalid PIGRATION_STEPS %q: %v\n", s, err)
			os.Exit(1)
		}
		opts = append(opts, migrator.Steps(n))
	}
	if b := os.Getenv("PIGRATION_BATCH"); b != "" {
		k, err := strconv.Atoi(b)
		if err != nil {
			fmt.Fprintf(os.Stderr, "pigration: invalid PIGRATION_BATCH %q: %v\n", b, err)
			os.Exit(1)
		}
		opts = append(opts, migrator.Batch(k))
	}
	if os.Getenv("PIGRATION_ALLOW_FRESH") == "1" {
		opts = append(opts, migrator.AllowFresh())
	}

	cmd := os.Getenv("PIGRATION_CMD")
	switch cmd {
	case "up":
		res, err := migrator.Up(ctx, pool, opts...)
		fail(err)
		printApplied("Applied", res)
	case "down":
		res, err := migrator.Down(ctx, pool, opts...)
		fail(err)
		printRolledBack(res)
	case "fresh":
		res, err := migrator.Fresh(ctx, pool, opts...)
		fail(err)
		printApplied("Applied (fresh)", res)
	case "status":
		st, err := migrator.Status(ctx, pool, opts...)
		fail(err)
		printStatus(st)
	default:
		fmt.Fprintf(os.Stderr, "pigration: unknown command %q\n", cmd)
		os.Exit(1)
	}
}

func fail(err error) {
	if err != nil {
		fmt.Fprintf(os.Stderr, "pigration: %v\n", err)
		os.Exit(1)
	}
}

func printApplied(label string, res migrator.Result) {
	if len(res.Applied) == 0 {
		fmt.Println("Nothing to migrate.")
		return
	}
	fmt.Printf("%s (batch %d):\n", label, res.Batch)
	for _, n := range res.Applied {
		fmt.Printf("  + %s\n", n)
	}
}

func printRolledBack(res migrator.Result) {
	if len(res.RolledBack) == 0 {
		fmt.Println("Nothing to roll back.")
		return
	}
	fmt.Println("Rolled back:")
	for _, n := range res.RolledBack {
		fmt.Printf("  - %s\n", n)
	}
}

func printStatus(st []migrator.MigrationStatus) {
	if len(st) == 0 {
		fmt.Println("No migrations registered.")
		return
	}
	fmt.Printf("%-40s %-10s %s\n", "MIGRATION", "STATUS", "BATCH")
	for _, s := range st {
		status := "applied"
		batch := ""
		if s.Pending {
			status = "pending"
		} else if s.Batch != nil {
			batch = strconv.Itoa(*s.Batch)
		}
		fmt.Printf("%-40s %-10s %s\n", s.Name, status, batch)
	}
}
`))

// RenderRunner renders the throwaway `go run` entrypoint that blank-imports the
// migrations package and dispatches to the requested migrator function based on
// environment variables.
func RenderRunner(migrationsImport string) (string, error) {
	var b strings.Builder
	if err := runnerTmpl.Execute(&b, runnerData{MigrationsImport: migrationsImport}); err != nil {
		return "", fmt.Errorf("rendering runner: %w", err)
	}
	return b.String(), nil
}
